### ISSUE TITLE
Add pre/post flag for RequiredParameterNode

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#1600]
AFAIK `RequiredParameterNode` could be contained either in `ParametersNode#requireds` or in `ParametersNode#posts`. To distinguish them (in a visitor) we should have a state somewhere. It would simplify a logic if `RequiredParameterNode` indicates itself whether it's a pre or a post parameter.

**Comment by eregon** [comment]
Alternatively it could be different node types like PreRequiredParameterNode and PostRequiredParameterNode, which would be nice as then different visitor methods would be called, which is quite useful.
As a note for KeywordParameterNode whether it's required or optional is represented by value being null/nil-able, so that's already known.

**Comment by eregon** [comment]
@jemmaissroff @enebo Any thought on this? Wouldn't it simplify compilation to have two separate nodes for this or a flag?

**Comment by enebo** [comment]
@eregon I do not use a visitor to process parameter values.  I just process `requireds` first then `optionals` and so on. 

My thought would be if you are using a visitor you could just process ParametersNode and not have it continue visiting beneath that node since you have all the types sorted by order you need to process them.  

If that doesn't work or you don't like it I guess I don't care if a flag is added.  I don't really see this as a new node type but if we do it that way we should make an interface so we can process them both the same (or making one the subtype of another).

**Comment by eregon** [comment]
I see.
I think there is no need for a common interface because they need to be compiled differently, e.g. https://github.com/oracle/truffleruby/blob/5dbdd3187e8a03435abe4560f9472a7b835f3073/src/main/java/org/truffleruby/parser/LoadArgumentsTranslator.java#L306
i.e. it must be a negative index for post-required -- added to # of positional arguments passed --, and it's a positive index for pre-required.

As we can see in https://github.com/oracle/truffleruby/blob/5dbdd3187e8a03435abe4560f9472a7b835f3073/src/main/java/org/truffleruby/parser/LoadArgumentsTranslator.java that has some state and tight coupling which could be removed with this improvement.

**Comment by enebo** [comment]
> I see. I think there is no need for a common interface because they need to be compiled differently

Yep.  You are right they are different.  Not sure why I thought that.

**Comment by eregon** [comment]
For destructured posts we would indeed still need the state, unless the destructure node would indicate the negative index of it from the end or so. This wouldn't remove the state for handling ParametersNode entirely, but it would make it easier to handle simple pre and post RequiredParameterNode, as at least for compilation they are fairly different.

**Comment by kddnewton** [comment]
Because we don't have this on destructured parameters, it seems like it would be confusing to the consumer to have it on required parameters.
