### ISSUE TITLE
Consider IntegerNode storing base and not a flag

### ISSUE THREAD

**Issue by enebo** [ruby/prism#1695]
If you look at functions like `str2inum` they work with base but IntegerNode requires examining boolean flags to determine base.  There are not many bases so this is a fairly minor enhancement.

**Comment by kddnewton** [comment]
I can't make this another field without adding a bunch of bytes because of alignment... ugh.

What I can do (which is a little hacky, but kind of funny) is that I could rearrange the flags so that they're:

* binary
* decimal
* octal
* hexadecimal

If we did that, then you could get the base by:

```
((flags ^ ~decimal) << 1) || 10
```

We could put tests in here to ensure that stays correct. What do you think?

**Comment by eregon** [comment]
Doesn't `str2inum` or so accept a base of `0` and then it auto-detects what to do? (and so flags are not necessary, since we're reusing the logic for Kernel#Integer)
I'm using [ConvertBytes.bytesToInum()](https://github.com/oracle/truffleruby/blob/070598d468848fae29f6ffcebf64c4348239c5d4/src/main/java/org/truffleruby/parser/YARPTranslator.java#L1528) in TruffleRuby, which IIRC comes from JRuby.

**Comment by enebo** [comment]
@eregon yeah I suppose the overall cost of thoses ifs+switch is not a big deal but if we can just get it why not use it?

@kddnewton I like the idea.  As @eregon points out we have logic to examine the string but if we ever make the decision to use some binary representation for integers that will not work any more.  So I think this will future-proof things if we do decide to do that later.
