### ISSUE TITLE
Consider adding a flag for implicit rest parameter in a block (`proc { |a,| }`)

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#1722]
A block with trailing `,`  in a parameters list means a rest parameter similar to explicit declaration `|a, *|`.

But CRuby behaves a bit differently in this case and a block has different arity:

```ruby
proc { |a,| }.arity # => 1
proc { |a, *| }.arity # => -2
```

To support this we need either node locations serialised or explicit flag.

**Comment by eregon** [comment]
This feels like missing information because there is no reasonable way to implement the compatible semantics without this information (well there is with the location but that seems pretty hacky).
BTW @andrykonchin filed https://bugs.ruby-lang.org/issues/19971 but even if that gets fixed it would only apply for 3.3+, so we'd still need it anyway in Prism.

@kddnewton Do you think this could be added soon?

Otherwise we might need to workaround for now by serializing the RestParameterNode#operator_loc location, i.e. a partial revert of https://github.com/ruby/prism/commit/c82a9dad64882f0698b2a0db4c37896af7ef5f42 with different field marked as `semantic_field: true`.
