### ISSUE TITLE
Locals contains surprising `*`, `**` and `&` in case of anonymous rest/keyword rest/block parameters

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#1737]
So e.g. for `def a(b, **) end` method definition `DefNode.locals` contains `[:b, :**]` what seems incorrect and not intentional.

```
bin/parse -e 'def a(b, **) end'
@ ProgramNode (location: (1,0)-(1,16))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,16))
    └── body: (length: 1)
        └── @ DefNode (location: (1,0)-(1,16))
            ├── name: :a
            ├── name_loc: (1,4)-(1,5) = "a"
            ├── receiver: ∅
            ├── parameters:
            │   @ ParametersNode (location: (1,6)-(1,11))
            │   ├── requireds: (length: 1)
            │   │   └── @ RequiredParameterNode (location: (1,6)-(1,7))
            │   │       └── name: :b
            │   ├── optionals: (length: 0)
            │   ├── rest: ∅
            │   ├── posts: (length: 0)
            │   ├── keywords: (length: 0)
            │   ├── keyword_rest:
            │   │   @ KeywordRestParameterNode (location: (1,9)-(1,11))
            │   │   ├── name: nil
            │   │   ├── name_loc: ∅
            │   │   └── operator_loc: (1,9)-(1,11) = "**"
            │   └── block: ∅
            ├── body: ∅
            ├── locals: [:b, :**]
            ├── def_keyword_loc: (1,0)-(1,3) = "def"
            ├── operator_loc: ∅
            ├── lparen_loc: (1,5)-(1,6) = "("
            ├── rparen_loc: (1,11)-(1,12) = ")"
            ├── equal_loc: ∅
            └── end_keyword_loc: (1,13)-(1,16) = "end"
```

**Comment by eregon** [comment]
At least these variables do not seem to be exposed at the Ruby level:
```
$ ruby -e 'def m(*,**,&); p binding.local_variables; end; m'
[]
```

**Comment by enebo** [comment]
This is how we implement anonymous variables in old parsers as well.  We use those names for forwarding in case of zsuper(forwardingsuper).  

As @eregon said we implement reflective methods to only display valid ident names so this is ok.

**Comment by enebo** [comment]
A significant difference with prism where I am conflicted:

```text
ruby -I. ./bin/parse -e 'def a(...);end'
@ ProgramNode (location: (1,0)-(1,14))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,14))
    └── body: (length: 1)
        └── @ DefNode (location: (1,0)-(1,14))
            ├── name: :a
            ├── name_loc: (1,4)-(1,5) = "a"
            ├── receiver: ∅
            ├── parameters:
            │   @ ParametersNode (location: (1,6)-(1,9))
            │   ├── requireds: (length: 0)
            │   ├── optionals: (length: 0)
            │   ├── rest: ∅
            │   ├── posts: (length: 0)
            │   ├── keywords: (length: 0)
            │   ├── keyword_rest:
            │   │   @ ForwardingParameterNode (location: (1,6)-(1,9))
            │   └── block: ∅
            ├── body: ∅
            ├── locals: [:"..."]
            ├── def_keyword_loc: (1,0)-(1,3) = "def"
            ├── operator_loc: ∅
            ├── lparen_loc: (1,5)-(1,6) = "("
            ├── rparen_loc: (1,9)-(1,10) = ")"
            ├── equal_loc: ∅
            └── end_keyword_loc: (1,11)-(1,14) = "end"
```

I actually make *,**,& in this case as new variables to match old way but I am wonder if I could get away with a single variable for all arguments?

**Comment by eregon** [comment]
I agree with @andrykonchin it sounds to me like this is CRuby implementation details leaking into Prism (e.g. `...` is at least currently CRuby-specific).
There is no `&` or `...` variable from the Ruby user point of view.

So I think Prism should not include those in `locals`, at least from a syntax POV it doesn't make sense.

Or if Prism supports hidden/temporary variables then they should be prefixed consistently, e.g. with `%`. But I think this would be weird for tools relying on `locals` being Ruby local variables, which seems a reasonable assumption for tools.

**Comment by eregon** [comment]
OTOH I remember an issue that it would be nice if `...` could be observed in a debugger in the local variables view.
But since `...` is not a Ruby object I don't think this can really work anyway.

Maybe this is another use case for desugaring, i.e. without it there is no such `&/*/**/...` variable in locals/anywhere, but after desugaring we could have hidden/temporary variables in locals and `KeywordRestParameterNode` would have `name = :"**"`.
Having hidden/temporary variables in locals would be very convenient for desugaring.

So I think either `**` etc should be present everywhere or nowhere, not just in locals but then not in `KeywordRestParameterNode`. Nowhere seems better for tools.

**Comment by enebo** [comment]
@eregon right now I have:

```java
StaticScope staticScope = createStaticScopeFrom(node.locals, StaticScope.Type.LOCAL);
```

Your suggestion I can accommodate but I would prefer for serialization we provide these (which means they show up in our trees).  It just makes this simpler.  The `...` is a case where I have to modify the staticscope at that point but since I am making a hidden `...` variable I can change it to just use that.

For syntax tools I think that is not important to me but it is hard to talk about the AST when we mean all trees or just a specific one.  I am only suggesting it for building/compilaton.

**Comment by kddnewton** [comment]
@enebo this is fixed in the most recent version of prism, `def foo(...); end` adds `*`, `&`, and `...`.

Overall these locals are there so that the parser can know when `bar(*)` is allowed (if you're within a context where `*` is in the local table or not). So either way, I need these in the C API. I might be okay with hiding them from the Java/Ruby API, but I do think it's nice to be able to tell in some methods where you can use `*` or `&`.

**Comment by andrykonchin** [comment]
By the way I've noticed a minor issue with forwarding anonymous arguments in Prism. 

The forwarding doesn't work in lambda/proc and leads to `no anonymous rest parameter` (and similar) `SyntaxError` in CRuby (3.2). But Prism doesn't return errors and adds `*` (and others) to the `locals` field, e.g. 

```ruby
def bar(*rest) rest end
proc { |a, *| bar(*) }.call(1, 2, 3)
```

**Comment by enebo** [comment]
> @enebo this is fixed in the most recent version of prism, `def foo(...); end` adds `*`, `&`, and `...`.

I think you meant `**` and not `...` for the fix but that is great.  I have some code I can delete once I merge that.
 
> I might be okay with hiding them from the Java/Ruby API, but I do think it's nice to be able to tell in some methods where you can use `*` or `&`.

I absolutely want these in locals.  There is a impl flag now in template generation so if TR wants to not have these they can do that with a small change.

**Comment by eregon** [comment]
> if TR wants to not have these they can do that with a small change.

We can deal with the extra variables in TruffleRuby, no big deal. @andrykonchin raised the issue because we weren't sure it's intentional to expose these hidden variables to Prism users (mostly Ruby users).
Since in Java we intern all constants as j.l.String or symbols we can quickly compare `*/**/&` using Java `==`.

@andrykonchin Regarding https://github.com/ruby/prism/issues/1737#issuecomment-1779698409 could you file another issue and include this?
```
ruby -ve 'proc { |a, *| bar(*) }.call(1, 2, 3)'
ruby 3.3.0dev (2023-10-01T10:34:55Z prism-call-node-co.. fcd1aad312) [x86_64-linux]
-e:1: no anonymous rest parameter
-e: compile error (SyntaxError)
```

**Comment by kddnewton** [comment]
Oh man... I actually expected `proc { |a, *| bar(*) }.call(1, 2, 3)` to work. It doesn't? That's wild....
