### ISSUE TITLE
Numbered parameter mismatched Error strings

### ISSUE THREAD

**Issue by enebo** [ruby/prism#1820]
Two basic SyntaxError strings:

```ruby
-> { _1; -> { _2 } }
```

```text
Expected SyntaxError ((?m-ix:numbered parameter is already used in))
but got: SyntaxError ((eval):1: Numbered parameter is already used in outer scope)
```

AND:

```ruby
 _1 = 0
  proc { _1 }.call("a")
```

```text
Expected SyntaxError ((?-mix:_1 is reserved for numbered parameter))
but got: SyntaxError ((eval):1: Token reserved for a numbered parameter)
```

**Comment by kddnewton** [comment]
The second one has been fixed on `main`. @eregon any chance you can update ruby/spec such that it checks for that regex case-insensitive?

**Comment by eregon** [comment]
We can adapt the specs if needed to allow either.
But shouldn't Prism be as much as feasible compatible in its SyntaxError messages? (unless the CRuby message is pretty unclear, then it can be worth to improve it, but there is almost always a compatibility cost to change those things).
I think exception messages starting with an uppercase letter are very rare if they exist at all in CRuby, i.e. I think they all/almost all start with a lowercase letter.

**Comment by kddnewton** [comment]
It's a complete mix.

We have things like `Invalid break`, `Invalid next`, `Invalid octal digit`, as well as a bunch of lowercase ones. It's not at all standardized.

On the other hand, we have a style guide for our error messages and are attempting to standardize them. I'd prefer that we keep them capitalized since we have consistency there.

I agree with the idea of compatibility to a certain extent, but at the same time we're going to provide many more error messages and many more specific error messages than the current Ruby parser, so this is a place where we're going to have to deviate.

**Comment by eregon** [comment]
From experience with exception messages in TruffleRuby, it's almost never worth the cost to deviate, there is basically always a gem depending on an exception message and it's a pain to update those.
Of course for completely new errors or so it's more free.

> We have things like Invalid break, Invalid next, Invalid octal digit, as well as a bunch of lowercase ones. It's not at all standardized.

I think these `Invalid` are about the only uppercase error messages.
All TypeError, ArgumentError etc from CRuby start with a lowercase letter, isn't it? I would strongly recommend to not try to change that but instead change the style guide, because it's only going to cause needless friction towards making Prism the default parser in CRuby and using Prism in tools instead of Ripper/parser gem.

Getting some quick stats in ruby/ruby:
```
git grep -P 'rb_raise[^"]+"[A-Z]' | wc -l
154
git grep -P 'rb_raise[^"]+"[a-z]' | wc -l
1350
```
And amoung these 154 many of them are class/module names.

`git grep 'compile_error('` also shows most (all?) of the SyntaxError are lower-case.
`Invalid break` comes from compile.c, which may be the reason for the inconsistency.

**Comment by andrykonchin** [comment]
Does it make sense to have two "modes" of the parser for raising exception messages - CRuby compatible and not compatible modes?

As a replacement of the current CRuby parser - we need compatibility. But when Prism is used as a gem for linters/formatters/etc - such compatibility isn't required. And the more a message is informative/helpful the better.

**Comment by kddnewton** [comment]
I would really prefer to avoid "modes" to be honest. I'm generally scared of the divergence. I've pushed back on this for the syntax tree as well for this same reason.

What I would prefer would be to provide a rich enough interface that it can satisfy all consumers. In this case I believe that eventually means providing different error classes that subclass `SyntaxError` so people can rescue individually (since right now, people rescue `SyntaxError` and then parse out the message).
