### ISSUE TITLE
Ruby rejects `a....b` but Prism accepts it.

### ISSUE THREAD

**Issue by tompng** [ruby/prism#1829]
It's parsed as `(a...).b`
```ruby
Prism.parse('a....b').success? #=> true
eval('a....b') #=> syntax error, unexpected '.', expecting end-of-input (SyntaxError)
```

**Comment by nevinera** [comment]
Well, yours definitely looks simpler, unless having specific error messages is worth some trouble here :-)

I'd love it if someone would pick through my PR even if it's not destined for a merge - I'm just getting started on the repo, and I'd like to improve my approaches, mergeable or not.

**Comment by makenowjust** [comment]
@nevinera This bug is because the associativity of `..` and `...` is wrong. So, it would need to be fixed in my way.

Modifying my implementation to produce a specific error message is not hard. You may modify it after it has been merged. (Honestly, I'm not sure it is helpful for developers because `....` seems rare and terrible and developers can easily find this without the specific error.)

**Comment by nevinera** [comment]
I agree, and would not have posted my pr if I had seen yours first. I left it up in draft because I wanted feedback on it, but certainly it should not be merged. :-)
