### ISSUE TITLE
Prism accepts MultiTargetNode in method arguments `f((*))`

### ISSUE THREAD

**Issue by tompng** [ruby/prism#1832]
Prism accepts these codes. Ruby rejects them.
```ruby
f((*))
f((a,b))
f(((a,*,b),*))
```

**Comment by pcai** [comment]
I looked at the `f((*))` case briefly and found this:

https://github.com/ruby/prism/blob/b83a639f9254e45336985f02cd97062b86f7a69b/src/prism.c#L13642-L13659

The else branch in L13656 is problematic because it creates the MultiTargetNode using the splat node as a target without any additional checks. But I'm not sure how to update this to check the current context and disallow it inside method arguments.
