### ISSUE TITLE
[COMPILER] Fix `=>` in method args 

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#1894]
For example:

`a("a"=>0)`

Found in this test:

RUBY_ISEQ_DUMP_DEBUG=prism make test-all TESTS=../test/-ext-/test_scan_args.rb

**Comment by thdaraujo** [comment]
I would like to work on this one, if possible. Hope you don't mind me asking a bunch of questions. :laughing: 

I guess the file you're talking about is [this one](https://github.com/ruby/ruby/blob/8e80cad9e9f70948c1c2d472b66a94c4151268f4/test/-ext-/test_scan_args.rb#L4). That's quite helpful.

**Comment by jemmaissroff** [comment]
Yes, happy to help how I can! I would use the minimal example more than the test, at least to start. For instance, if you write a `test.rb` file with `RubyVM::InstructionSequence.compile_prism('a("a" => 0)')`, you should see the bug, and can then use `make lldb` or `make run` to test more incrementally

**Comment by thdaraujo** [comment]
Thanks, @jemmaissroff !

I was able to reproduce the issue on Ruby 3.3.0-preview3. It seems to also affect keyword arguments (as in `'a(a: 0)'`. 

Reproduction:
```
RubyVM::InstructionSequence.compile_prism('a("a" => 0)')

<compiled>: <compiled>: argument stack underflow (-1701) (SyntaxError)
```

As there was no difference in the generated AST, I believe this is caused by passing `parent = NULL` for `prepare_iseq_build` [here](https://github.com/ruby/ruby/blob/bd2b6b702cf43fb25562bdf8b1929d06ed3fcd98/iseq.c#L1402):
```
prepare_iseq_build(iseq, rb_fstring_lit("<compiled>"), file, path, first_lineno, &code_location, -1, NULL, 0, ISEQ_TYPE_TOP, Qnil, &option);
```

When `parent` is null, `err_info` is not set to `false`:
https://github.com/ruby/ruby/blob/bd2b6b702cf43fb25562bdf8b1929d06ed3fcd98/iseq.c#L600-L601

And then the syntax error is raised here:
https://github.com/ruby/ruby/blob/bd2b6b702cf43fb25562bdf8b1929d06ed3fcd98/iseq.c#L702-L707

I have a WIP fix that I'll test tomorrow here: 
https://github.com/ruby/ruby/pull/9058
