### ISSUE TITLE
[COMPILER] Compiling array within a hash

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#2015]
Minimal repro:

```
{[] => 1}
```
leads to `method `hash' called on hidden T_ARRAY object`

Found from: `RUBY_ISEQ_DUMP_DEBUG=prism make test/coverage/test_coverage.rb`

**Comment by paracycle** [comment]
There is a similar problem that exhibits itself with a similar message, which can be reproduced by:
```ruby
RubyVM::InstructionSequence.compile_prism(<<~RUBY).eval
  def foo a: [], b: []
    p a
    p b
  end
  foo(a: [Symbol])
RUBY
```
and it outputs: 
```
[Symbol]
<compiled>:2:in `p': method `inspect' called on hidden T_ARRAY object (0x00000001033d4de0 flags=0xa00002807) (NotImplementedError)
        from <compiled>:2:in `foo'
        from <compiled>:4:in `<compiled>'
        from ../test.rb:39:in `eval'
        from ../test.rb:39:in `<main>'
```
Note that since the second optional param is not passed, it causes an error on the `p b` line, so this version of the error looks like a default parameter bug.

I found this by isolating it from the failure of `RUBY_ISEQ_DUMP_DEBUG=prism make ../test/ostruct/test_ostruct.rb`

**Comment by paracycle** [comment]
Oh I think I know what's wrong with #2016. The PR checks if `element` is any of the types `PM_NODE_ARRAY`, `PM_NODE_HASH` and `PM_NODE_RANGE`, but the element won't be any of those types for a hash, it will be `PM_NODE_ASSOC`.

Now, `PM_NODE_ASSOC` also has a static literal check of its own, but that only checks to see if the `value` (not the `key`) is an array, hash or range.

So, none of our code actually makes the `PM_HASH_NODE` in the above example to not be a static literal.

**Comment by paracycle** [comment]
OK, I have what I think is a fix here: https://github.com/ruby/prism/pull/2055 and a test that passes on ruby/ruby with that change here: https://github.com/ruby/ruby/pull/9215
