### ISSUE TITLE
Skip depth 0 for local lookup with positive depth offset

### ISSUE THREAD

**Issue by eightbitraptor** [ruby/prism#2184]
Created from https://github.com/ruby/ruby/pull/9544

**Comment by kddnewton** [comment]
I did a little work on this, but there is more to do here. Ideally we should be skipping the scopes that will definitely not have the local because they were injected by CRuby. More details in the PR on CRuby.

Since this is working and it's fine for most cases, I'm changing this milestone to 3.4.0. This is a lower priority now than getting bugs fixed.
