### ISSUE TITLE
Don't use `mmap` when calling `pm_parse` from the Ruby API

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#2535]
It's incredibly unlikely, but possible for the underlying bytes to be modified between the time the file is parsed and the time when we reify the Ruby AST. Since we're going to be returning the entire source to Ruby as a part of the `Prism::Source` object, there's not a ton of benefit to using `mmap` in these circumstances anyway. Let's keep it only for the C API.

**Comment by eregon** [comment]
I don't follow, isn't it safe to use `mmap` to gets all the file contents? Then one could create a Ruby String from the result of mmap, which will copy, and that `RSTRING_PTR(str)` could be used to parse, no?

I think `fread` is quite a bit slower because e.g. it does not benefit from caching.

**Comment by kddnewton** [comment]
I don't think we have any guarantee that between the time we call `mmap` and the time we call `rb_str_new` even if they're sequential that the underlying bytes haven't changed and that it's safe to `memcpy`. I was trying to find a way to determine if the mmap was dirty but couldn't find out.

**Comment by eregon** [comment]
To clarify, what I meant is one could `VALUE str = rb_str_new(mmap(...)); yp_parse(RSTRING_PTR(str))`.
Then it would parse on the copy, so that cannot change.

I think you're getting at whether it's safe to read from the pointer returned by mmap and how is that affected if the file is changed concurrently. Also what happens if the file is shrinked or appended to, in that case the file size from `fstat()` might be stale.
I would guess `mmap()` has protections for this and might possibly expose an older consistent snapshot of the file.
But it doesn't seem clearly specified from the man page, e.g. under `MAP_PRIVATE` (which Prism uses):

> It is unspecified whether  changes  made to the file after the mmap() call are visible in the mapped region.

And in NOTES:

> The effect of changing the size of the underlying file of a mapping on the pages that
> correspond to added or removed regions of the file is unspecified.

Out of curiosity, was using mmap causing a problem in practice?

**Comment by kddnewton** [comment]
From everything I've read (including the docs that you included) mmap has no protections for this. Yes, this problem came from a user where they got a BUS error relatively consistently.
