### ISSUE TITLE
`Prism::Translation::RubyParser` - Match operator

### ISSUE THREAD

**Issue by presidentbeef** [ruby/prism#2926]
`=~` with a regex literal on the right-hand side should be a `match3`, but it's creating a regular `call`:

```ruby
RubyParser.new.parse('a =~ /a/')
 => s(:match3, s(:lit, /a/), s(:call, nil, :a))
> Prism::Translation::RubyParser.parse('a =~ /a/')
 => s(:call, s(:call, nil, :a), :=~, s(:lit, /a/))
```

Note the opposite is already handled:

```ruby
RubyParser.new.parse('/a/ =~ a')
 => s(:match2, s(:lit, /a/), s(:call, nil, :a))
> Prism::Translation::RubyParser.parse('/a/ =~ a')
 => s(:match2, s(:lit, /a/), s(:call, nil, :a))
```

(Tested with Prism 0.30.0)

**Comment by kddnewton** [comment]
Interesting. The reason we did it this way is because `/(?<foo>)/ =~ ""` will implicitly create local variables for named capture groups, but `"" =~ /(?<foo>)/` won't. So semantically they are very different. I will make it match for the translation layer, but that's probably worth addressing in the ruby_parser gem.

**Comment by kddnewton** [comment]
Ahh I see, I didn't catch that initially, thanks that makes a lot more sense.
