### ISSUE TITLE
Prism accepts invalid usage of `==` with newline that Ruby rejects

### ISSUE THREAD

**Issue by Earlopain** [ruby/prism#3008]
Example code:

```rb
1 if 2 == 3 ==
4
```

Ruby:
```
test.rb:1: syntax error, unexpected == (SyntaxError)
1 if 2 == 3 ==
            ^~
```

Prism:

```rb
#<Prism::LexResult:0x00007ba5316a4f80
 @comments=[],
 @data_loc=nil,
 @errors=[],
 @magic_comments=[],
 @source=#<Prism::ASCIISource:0x00007ba531554e78 @offsets=[0, 15, 17], @source="1 if 2 == 3 ==\n4\n", @start_line=1>,
 @value=
  [[INTEGER(1,0)-(1,1)("1"), 2],
   [KEYWORD_IF_MODIFIER(1,2)-(1,4)("if"), 1025],
   [INTEGER(1,5)-(1,6)("2"), 2],
   [EQUAL_EQUAL(1,7)-(1,9)("=="), 1],
   [INTEGER(1,10)-(1,11)("3"), 2],
   [EQUAL_EQUAL(1,12)-(1,14)("=="), 1],
   [IGNORED_NEWLINE(1,14)-(2,0)("\n"), 1],
   [INTEGER(2,0)-(2,1)("4"), 2],
   [NEWLINE(2,1)-(3,0)("\n"), 1],
   [EOF(3,0)-(3,0)(""), 1]],
 @warnings=
  [#<Prism::ParseWarning @type=:void_statement @message="possibly useless use of == in void context" @location=#<Prism::Location @start_offset=0 @length=16 start_line=1> @level=:verbose>]>
```

**Comment by souadfettah** [comment]
Can you try this : 
`1 if (2 == 3) && (3 == 4)
`

**Comment by Earlopain** [comment]
That just looks like valid syntax, no? I'm not quite sure what you mean.

**Comment by souadfettah** [comment]
> That just looks like valid syntax, no? I'm not quite sure what you mean.

If your intention was to check whether 2 == 3 and then, based on the result, decide whether to return 1, you would write it like this:
`1 if 2 == 3`

This code will return nil (since 2 == 3 is false), and 1 will not be returned because the condition is false.


If your intention was to check multiple conditions, such as 2 == 3 and 3 == 4, and then return 1 if both conditions are true, you should write:
`1 if (2 == 3) && (3 == 4)`

This checks if both 2 == 3 and 3 == 4 are true. Since neither is true, the result will be nil, and 1 will not be returned.

**Comment by tompng** [comment]
I found some similar codes that prism accepts and parse.y rejects.
```ruby
p 1==1==1
p 1<=>1<=>1
a = 1==1==1
1 && 1==1==1
def f()=1==1==:f
...1==1==1
1 if 2 == 3 == 4 # Reported here
p 1..1..1
a = 1..1..1
1 and 1..1..1
def f()=1..1..:g
1 if 1..1..1
```
