### ISSUE TITLE
Revisit strings

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#579]
Currently there are a couple of places that we attach strings to the tree. The first is `CallNode#name` which is necessary because some method names can be synthesized, e.g., `foo=`, `call`, etc. This is handled on its own and is fine.

The other places are `RegularExpressionNode#unescaped`, `StringNode#unescaped`, `SymbolNode#unescaped`, and `XStringNode#unescaped`. These are necessary in the case that we have escape sequences in the middle of these nodes. To make it easier to compile, we unescape those values as parse time.

To unescape them we make two passes. The first is while we're lexing. Whenever we encounter an escape (`\`), we call the unescape function to determine how many characters the escape takes (`\a` takes 2, `\C-\M-x` takes 7, etc.). Then, when we go to create one of these nodes that has the string attached, we make _another_ pass through the string and build the `yp_string_t` that will be attached.

Instead, it would be more efficient to build the escaped version while we lex. We could do this with a single `yp_string_t` that we keep on the parser (named something like `current_string`). Because the parser is only calling `parser_lex` one token at a time, we can always use the most recent value whenever we're about to handle a `YP_TOKEN_STRING_CONTENT` or `YP_TOKEN_CHARACTER_LITERAL` (the only tokens that actually generates this kind of content). The nodes can then copy the `yp_string_t` struct onto themselves and the next time one would be generated the parser can clear out the previous value with a `memset`. At this point ownership of any allocated memory on the string passes to the nodes that now own it, so we'll be okay from a memory perspective.

**Comment by enebo** [comment]
@kddnewton I think this is also a reasonable issue to consider calculating code_range (CR) for Strings.  I don't personally remember whether MRI does this during parse but it is free work since we need to walk strings anyways.  @nirvdrum may recall the amount of CR processing MRI does during parse.

There should be no semantic issue with this,

**Comment by enebo** [comment]
code range is a flag associated with strings which have the following values:

  1. UNKNOWN - we haven't walked it yet but it needs to be
  2. 7BIT - We know the contained characters are all 7BIT ASCII and it is an encoding which supports ASCII values
  3. VALID - We know it is a valid string for the encoding specified
  4. BROKEN - We know it contains invalid bytes for the specified encoding

MRI has code to do this walking but for biggest bang you would want this is your main loop when you process the strings.

**Comment by enebo** [comment]
I am not sure if this will matter at all but knowing something is 7BIT could allow some fast-pathing within prism itself.  I do not think prism is interacting too much with the strings it processes but knowing you can just byte walk is a nice perf boost.

**Comment by nirvdrum** [comment]
Taking a quick look at _parse.y_ in CRuby, it detects the code range for `here_document` and `parse_ident`. Although, scanning isn't quite right. Since it needs to look at every byte to determine the start and end points for the string or identifier, it does a cheap code range check as it goes. It might only detect `7BIT`. Detecting `VALID` or `BROKEN` would require following rules for the current encoding and is thus more difficult to do in the simple pass the current parser is doing. Determining whether something is `7BIT` is a single byte comparison.

With that said, I think it would be valuable to implement UTF-8 code range checking. It's by far the most common encoding for strings and implementing its rules can be done in straightforward manner. You could use a local state machine rather than peeking ahead so it could still be done in a linear pass.

Determining the code range for all string literals and symbols would be great to have from the parser, perhaps limited to `US-ASCII`, `UTF-8`, and `ASCII-8BIT` so the parser doesn't balloon. I'm not familiar with the current string nodes, but I'd imagine we could have a simple enum with `UNKNOWN` as the default value. The caller can decide whether to use the computed value.

**Comment by eregon** [comment]
What's the advantage of the parser computing the code range?
If it's unused it's likely overhead.

At least in TruffleRuby I don't see how we could use this information if Prism provided it.
In Java on TruffleRuby we create java.lang.String from the byte[] and that cannot take advantage of the coderange.
And in Ruby we create RubyString from the serialized output and that cannot take advantage of a coderange either, it's always recomputed when creating the string.

I think it's best, fastest and simplest to just let the creation of the Ruby strings/Java strings/org.jruby.RubySymbol compute the coderange, when they copy the bytes.
