### ISSUE TITLE
Import Sorbet parser tests

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#638]

**Comment by KaanOzkan** [comment]
Thanks for this feature! I wanted to point that Sorbet parser tests are a subset of whitequark since they are [imported](https://github.com/sorbet/sorbet/blob/master/tools/scripts/import_whitequark.rb) as we do version bumps in case that context wasn't shared. Looks like the main difference is that yarp currently doesn't import `assert_diagnoses` tests so I'd expect adding support for that would be enough to effectively pull in all Sorbet parser tests.

**Comment by kddnewton** [comment]
Hey @KaanOzkan - I thought I saw some tests in Sorbet for checking that it could recover from specific syntax errors. Do you know where that might be? I can't seem to find them for some reason.

**Comment by KaanOzkan** [comment]
@kddnewton Yes those aren't imported so they live under a [different folder](https://github.com/sorbet/sorbet/tree/master/test/testdata/parser/error_recovery).

**Comment by kddnewton** [comment]
Ah-ha! Yeah these are the ones I want to import.

**Comment by kddnewton** [comment]
Closing this now since Emily is working on porting sorbet to prism so this no longer makes a lot of sense.
