### ISSUE TITLE
ImaginaryNode is missing information about kind of a numeric literal

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#768]
ImaginaryNode represents `1i` literal but doesn't provide any information about numeric part, just location in the source string.

Numeric part could be:
- integer (`1i`)
- float (`1.0i` or `0.1e2i`)
- or even rational (`1ri`)

It would be helpful if ImaginaryNode had a child node for the numeric literal e.g. `IntegerNode`, `FloatNode` etc.

**Comment by HParker** [comment]
This is intentional. YAPR tries to be agnostic to implementation. It is likely impossible for us to make an impartial decision about how to represent the numeric part. For example, different implementations might choose different integer cutoffs for different number types and YARP doesn't want to have an opinion about. Instead we leave it up to the library consumers to decide how to convert the source string into the type their VM chooses for that structure.

We talked about in the Ruby later providing some utility functions to make dealing with these types easier as a library consumer and I think that could be a nice addition. However, if this is needed for TruffleRuby, maybe that wouldn't help in your case.

Could you elaborate on what you need the numeric information for? Maybe I am misunderstanding what type of numeric information you want.

**Comment by enebo** [comment]
What I suggested above is how it is done in current parsers but that there are other ways to encode this.

  1. flags on Integer and Float.  One numeric field. This can even include base {octal|rational|imaginary}.
  2. megatypes  ImaginaryFloatNode,  ImaginaryRationalIntegerNode.  So long as you have less than 256 node types this is most space and time efficient.

**Comment by HParker** [comment]
@andrykonchin Let me know if this solution worked for you!

**Comment by andrykonchin** [comment]
Thank you. Will check soon.
